### PR TITLE
fix: responsiveness in homepage

### PR DESCRIPTION
**Pull request by ORKO06**
#16

### CODE REVIEW

**Review by CIPHERTron — CHANGES_REQUESTED** [review]
@ORKO06 Overall looks good to me.
Just some minor nitpicks in the recent articles section:
- Can we decrease the intensity of animation in the cards i.e. now almost 50% goes up when hovered but can we make it to either 20-25%?
- Can we have the text color changed to `#493434` instead of black?
- Can we have its text-align to be `justify`? (I'm not sure but I think justified will look better)
- Also, a small margin between Recent Articles heading and the cards would look great.

**Comment by ORKO06** [comment]
@CIPHERTron 
The intensity of animation in the cards is now set at 33% otherwise it won't have enough space to adjust the text in there.

**Comment by CIPHERTron** [comment]
> @CIPHERTron The intensity of animation in the cards is now set at 33% otherwise it won't have enough space to adjust the text in there.

We just need the heading of the article. Thus I don't think we require the amount of content it has right now. We can further reduce it.

**Review by CIPHERTron — CHANGES_REQUESTED** [review]
Just a few more nitpicks:
- Can we have more margin between the Recent Articles heading and the cards? because now, the first card on hovering hides the heading. It looks kinda odd in that instance
- Can we slow down the transition a bit? That would make the animation look smooth
- Also, we will be displaying only the heading of the articles. So, the amount of content can be further reduced :')

**Review by CIPHERTron — APPROVED** [review]
LGTM 🎉 
Thanks for the fix @ORKO06

**Pull request merged**
