### PR TITLE
Navbar logo, Scrollbar and typing error fixed

### PR DESCRIPTION
**Pull request by ratnakar5938**

### CODE REVIEW

**Comment by CIPHERTron** [comment]
@ratnakar5938 what about point 2 mentioned [here](https://docs.google.com/document/d/1m2yrc6qrd10krijZWlGEbc8uLzJ0qSBxTKQ-FYJDF0M/edit)?

**Comment by ratnakar5938** [comment]
> @ratnakar5938 what about point 2 mentioned [here](https://docs.google.com/document/d/1m2yrc6qrd10krijZWlGEbc8uLzJ0qSBxTKQ-FYJDF0M/edit)?

Done🚀

**Comment by CIPHERTron** [comment]
> > @ratnakar5938 what about point 2 mentioned [here](https://docs.google.com/document/d/1m2yrc6qrd10krijZWlGEbc8uLzJ0qSBxTKQ-FYJDF0M/edit)?
> 
> Done🚀

Here, after the first line, we need a `<br>` tag.
Also, change the colour of the text to what Hemant has set in Legacy page(it's only visible in mobile view)

**Comment by ratnakar5938** [comment]
msedge_qHci2KSk35
Done🚀

**Review by CIPHERTron — APPROVED** [review]

**Comment by CIPHERTron** [comment]
@ratnakar5938 
**Archive ka posts - maybe put the link to the full article when someone clicks the picture as well (right now it's just read more)**
This change is not done. Can you add the same link in the article image as well?

**Comment by ratnakar5938** [comment]
> @ratnakar5938 
> **Archive ka posts - maybe put the link to the full article when someone clicks the picture as well (right now it's just read more)**
> This change is not done. Can you add the same link in the article image as well?
> 

Okkk

**Comment by ratnakar5938** [comment]
Should I make a new PR or this will work @CIPHERTron

**Comment by CIPHERTron** [comment]
> Should I make a new PR or this will work @CIPHERTron

you can add it in this PR only. There'll be hardly 2-3 lines extra for this

**Pull request merged**
